server:
  port: 9000
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    api-a:
      path: /auth/**
      service-id: microservice-cloud-auth

    api-b:
      path: /buyer/**
      service-id: microservice-cloud-buyer

    api-c:
      path: /seller/**
      service-id: microservice-cloud-seller
